//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakeryprojEntities : DbContext
    {
        public BakeryprojEntities()
            : base("name=BakeryprojEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminlogin> Adminlogins { get; set; }
        public virtual DbSet<DailyOrder> DailyOrders { get; set; }
        public virtual DbSet<Rawmaterial> Rawmaterials { get; set; }
        public virtual DbSet<Productmaterial> Productmaterials { get; set; }
        public virtual DbSet<RawmaterialStock> RawmaterialStocks { get; set; }
        public virtual DbSet<OrderPlaced> OrderPlaceds { get; set; }
        public virtual DbSet<DispatchOrder> DispatchOrders { get; set; }
        public virtual DbSet<Dailyproduction> Dailyproductions { get; set; }
        public virtual DbSet<Logintable> Logintables { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryInfo> DeliveryInfoes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<State> States { get; set; }
    }
}
