//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customerid { get; set; }
        public string Customer1 { get; set; }
        public string Branch { get; set; }
        public string Address { get; set; }
        public string Mobileno { get; set; }
        public string Watsappno { get; set; }
        public Nullable<int> StateId { get; set; }
        public string GSTIN { get; set; }
        public string Code { get; set; }
    }
}
