//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dailyproduction
    {
        public int Dailyproductionid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<System.DateTime> Productdate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Goodproduct { get; set; }
        public Nullable<int> BadProduct { get; set; }
        public string ProductionStatus { get; set; }
        public Nullable<int> DispatchedQuantity { get; set; }
    }
}
