//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        public int DeliveryInfoId { get; set; }
        public string DeliveryBoyName { get; set; }
        public string WatsappNo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string VehicleNo { get; set; }
    }
}
