//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchOrder
    {
        public int DispatchOrdersId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Status { get; set; }
        public string InvoicePath { get; set; }
    }
}
