//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Productid { get; set; }
        public string Product1 { get; set; }
        public string Unit { get; set; }
        public string Baseprice { get; set; }
        public string HSNCode { get; set; }
        public string AltQty { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
    }
}
