//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productmaterial
    {
        public int Productmaterialid { get; set; }
        public Nullable<int> Productid { get; set; }
        public Nullable<int> Rawmaterialid { get; set; }
        public string Quantity { get; set; }
        public string Totalprice { get; set; }
        public string Units { get; set; }
    }
}
